version: "3.9"
services:
  backend:
    build: ./src/backend/
    ports:
      - "3000:3000"
    volumes:
      - ./src/backend:/usr/src/app
    depends_on:
      - "dbservice"
    networks:
      - db-network
    container_name: "backend"
  dbservice:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ft_transendance
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - db-network
    container_name: "dbservice"
    volumes:
      - pgdata:/var/lib/postgresql/data
  client:
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    build: "./client"
    container_name: "client"
    ports:
      - "5000:8080"
    command: yarn serve

networks:
  db-network:

volumes: 
     pgdata: